<template>
  <div class="generator">
    <h2><i class="fa fa-flask"></i> Custom sup-tRNA Generator</h2>

    <!-- 模型输入 -->
    <CodonInput @updateModel="updateModel" />

    <!-- 选择生成数量 -->
    <label for="sequence-count">Select Number of Sequences:</label>
    <select id="sequence-count" v-model="sequenceCount" class="select-box">
      <option v-for="count in sequenceOptions" :key="count" :value="count">
        {{ count }}
      </option>
    </select>

    <!-- 生成按钮 -->
    <button class="generate-btn" @click="generateSequence">
      Generate Sequences
    </button>

    <p class="note" v-if="localStatusMessage">{{ localStatusMessage }}</p>

    <!-- 父组件进度条 -->
    <div v-if="isGenerating" class="progress-container">
      <div class="progress-bar">
        <div class="progress" :style="{ width: progressValue + '%' }"></div>
      </div>
      <p>Progress: {{ progressValue }}%</p>
    </div>

    <p class="note">
      These sequences are entirely new and generated by artificial intelligence...
    </p>

    <!-- 子组件，监听事件：进度更新 / 任务完成 -->
    <SequenceResult
      @progress-updated="onProgressUpdated"
      @task-completed="onTaskCompleted"
    />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import axios from 'axios'
import CodonInput from './CodonInput.vue'
import SequenceResult from './SequenceResult.vue'

const sequenceOptions = [10, 50, 100, 500, 1000]
const sequenceCount = ref<number>(100)
const sequences = ref<string[]>([])
const defaultReverseCodon = ref('')
const selectedModel = ref('')
const localStatusMessage = ref('')

const progressValue = ref(0) // 父组件本地进度
const isGenerating = ref(false)
let intervalId: ReturnType<typeof setInterval> | null = null

function updateModel(modelName: string) {
  selectedModel.value = modelName
  console.log('Selected model updated to:', modelName)
}

/** 半假进度：只爬升到 90% */
function simulateProgress() {
  progressValue.value = 0
  if (intervalId) {
    clearInterval(intervalId)
    intervalId = null
  }
  intervalId = setInterval(() => {
    if (progressValue.value < 90) {
      progressValue.value += Math.random() * 5
      if (progressValue.value > 90) {
        progressValue.value = 90
      }
    } else {
      clearInterval(intervalId!)
      intervalId = null
    }
  }, 500)
}

/** 任务完成 => 冲到 100, 片刻后隐藏 */
function completeProgress() {
  if (intervalId) {
    clearInterval(intervalId)
    intervalId = null
  }
  progressValue.value = 100
  setTimeout(() => {
    isGenerating.value = false
  }, 600)
}

/** 将生成参数保存到 localStorage */
function saveParametersToLocalStorage() {
  const params = {
    model: selectedModel.value,
    reverseCodon: defaultReverseCodon.value,
    sequenceCount: sequenceCount.value,
  }
  localStorage.setItem('generationParameters', JSON.stringify(params))
  console.log('Saved generationParameters:', params)
}

/** 点击生成 */
async function generateSequence() {
  if (!selectedModel.value) {
    alert('Please select a model before generating sequences.')
    return
  }

  isGenerating.value = true
  // 父组件先开始爬升到90%
  simulateProgress()

  try {
    saveParametersToLocalStorage()

    const postData = new URLSearchParams()
    postData.append('model', selectedModel.value)
    postData.append('reverseCodon', defaultReverseCodon.value)
    postData.append('sequenceCount', sequenceCount.value.toString())

    const resp = await axios.post('/sample/process', postData, {
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    })

    // 后端此时也许只是说"已接收请求"，
    // 并未真正完成 => 不要 completeProgress() here
    sequences.value = resp.data.sequences || []
    localStorage.setItem('sequences', JSON.stringify(sequences.value))
    console.log('Server response saved sequences, but not necessarily completed.')
  } catch (err) {
    console.error('Error generating sequences:', err)
    alert('An error occurred while generating sequences. Please try again.')
    isGenerating.value = false
  }
}

/** 子组件发来的“进度更新”事件 => 若服务器给了真实进度 > 父组件当前值，就更新 */
function onProgressUpdated(realProgress: number) {
  console.log('Parent got progress-updated:', realProgress)
  if (realProgress > progressValue.value) {
    progressValue.value = realProgress
  }
}

/** 子组件发来的“任务完成”事件 => 冲到 100 */
function onTaskCompleted() {
  console.log('Parent got task-completed => jump 100')
  completeProgress()
}
</script>

<style scoped>
.generator {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  background: linear-gradient(to right, #eef2f3, #8e9eab);
  padding: 2em;
  border-radius: 8px;
  width: 100%;
  margin: 0 auto;
}

h2 {
  text-align: center;
  font-size: 2em;
  margin-bottom: 1em;
}

.select-box {
  margin: 1em 0;
  padding: 0.5em;
  font-size: 1em;
}

.generate-btn {
  background-color: #4caf50;
  color: white;
  padding: 0.8em 1.5em;
  border: none;
  border-radius: 5px;
  font-size: 1em;
  font-weight: bold;
  cursor: pointer;
  transition: background-color 0.3s ease;
}
.generate-btn:hover {
  background-color: #45a049;
}

.note {
  font-size: 1.1em;
  color: #555;
  margin-top: 1em;
  text-align: center;
}

.progress-container {
  width: 100%;
  margin-top: 1em;
  text-align: center;
}
.progress-bar {
  width: 100%;
  height: 20px;
  background-color: #e0e0e0;
  border-radius: 10px;
  overflow: hidden;
  margin-top: 10px;
}
.progress {
  height: 100%;
  background-color: #4caf50;
  transition: width 0.3s ease;
}
</style>
