<!-- src/pages/CodonGenerator/CodonGenerator.vue -->
<template>
  <div class="generator">
    <h2>
      <i class="fa fa-flask" aria-hidden="true"></i> Custom sup-tRNA Generator
    </h2>

    <!-- Model Input Component -->
    <CodonInput @updateModel="updateModel" />

    <!-- Sequence Count Selection -->
    <label for="sequence-count">Select Number of Sequences:</label>
    <select id="sequence-count" v-model="sequenceCount" class="select-box">
      <option v-for="count in sequenceOptions" :key="count" :value="count">
        {{ count }}
      </option>
    </select>

    <!-- Generate Button -->
    <button class="generate-btn" @click="generateSequence">
      Generate Sequences
    </button>
    <p class="note">
      These sequences are entirely new and generated by artificial intelligence. They do not correspond to any existing sequences, except by coincidence. The generation of these sequences is based on the RfamGen model proposed by Sumi, S., Hamada, M., and Saito, H. in the paper <i>“Deep generative design of RNA family sequences”</i> (<i>Nat Methods</i> 21, 435–443, 2024; <a href="https://doi.org/10.1038/s41592-023-02148-8" target="_blank">https://doi.org/10.1038/s41592-023-02148-8</a>). The training data for these sequences were obtained from the GtRNAdb database and additionally, we have compiled 1052 entries of tRNA-related data from various databases and literature sources, which will provide valuable insights into tRNA structure and function.
    </p>
    <!-- Sequence Result Component -->
    <SequenceResult />
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import axios from 'axios'
import CodonInput from './CodonInput.vue'
import SequenceResult from './SequenceResult.vue'

// Variable Declarations
const sequenceCount = ref(100)
const sequenceOptions = [10, 50, 100, 500, 1000] // Available sequence count options
const sequences = ref<string[]>([]) // Stores generated sequences
const defaultReverseCodon = ref('') // Default reverse codon
const selectedModel = ref('') // Selected model name

/**
 * Updates the selected model name.
 * @param {string} modelName
 */
function updateModel(modelName: string) {
  selectedModel.value = modelName
  console.log('Selected model updated to:', selectedModel.value)
}

/**
 * Saves generation parameters to local storage.
 */
function saveParametersToLocalStorage() {
  const parameters = {
    model: selectedModel.value,
    reverseCodon: defaultReverseCodon.value,
    sequenceCount: sequenceCount.value,
  }
  localStorage.setItem('generationParameters', JSON.stringify(parameters))
  console.log('Generation parameters saved to localStorage:', parameters)
}

/**
 * Generates sequences and saves them to local storage.
 */
async function generateSequence() {
  if (!selectedModel.value) {
    alert('Please select a model before generating sequences.')
    return
  }

  // Create a detailed confirmation message
  const confirmationMessage = `Are you sure you want to generate ${sequenceCount.value} sequences using the model "${selectedModel.value}"? This action may take a few moments.`

  // Show confirmation dialog
  const userConfirmed = window.confirm(confirmationMessage)
  if (!userConfirmed) {
    return // User canceled the operation
  }

  try {
    // Save generation parameters
    saveParametersToLocalStorage()

    // Prepare request parameters
    const params = new URLSearchParams()
    params.append('model', selectedModel.value)
    params.append('reverseCodon', defaultReverseCodon.value.toString())
    params.append('sequenceCount', sequenceCount.value.toString())

    // Send POST request
    const response = await axios.post('/sample/process', params, {
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    })

    // Update sequences
    sequences.value = response.data.sequences || []

    // Generate timestamp and save to local storage
    const generationTimestamp = Date.now().toString()
    localStorage.setItem('sequences', JSON.stringify(sequences.value))
    localStorage.setItem('timestamp_sequences', generationTimestamp)

    console.log(
      'Sequences and timestamp saved successfully:',
      generationTimestamp,
    )
  } catch (error) {
    console.error('Error generating sequences:', error)
    alert('An error occurred while generating sequences. Please try again later.')
  }
}
</script>

<style scoped>
.generator {
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  background: linear-gradient(to right, #eef2f3, #8e9eab);
  padding: 2em;
  border-radius: 8px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
  width: 100%;
  margin: 0 auto;
}

h2 {
  font-family: 'Playfair Display', serif;
  color: #2c3e50;
  font-size: 2em;
  margin-bottom: 1em;
  width: 100%;
  text-align: center;
  font-weight: bold;
  padding: 0.6em 1em;
  border-radius: 8px;
  background-color: #4caf50;
  color: white;
}

h2 i {
  margin-right: 10px;
  font-size: 1.6em;
}

.select-box {
  margin: 1em 0;
  padding: 0.5em;
  font-size: 1em;
}

.generate-btn {
  background-color: #4caf50;
  color: white;
  padding: 0.8em 1.5em;
  border: none;
  border-radius: 5px;
  font-size: 1em;
  font-weight: bold;
  cursor: pointer;
  transition: background-color 0.3s ease;
  margin-top: 1em;
}

.generate-btn:hover {
  background-color: #45a049;
}

.note {
  font-size: 1.1em;
  color: #555;
  margin-top: 1em;
  text-align: center;
}

select {
  padding: 0.8em;
  font-size: 1em;
  border: 1px solid #ddd;
  border-radius: 4px;
  margin-top: 0.5em;
  transition: border-color 0.3s ease;
  cursor: pointer;
}

select:focus {
  border-color: #4caf50;
  outline: none;
}

label {
  font-family: 'Roboto', sans-serif;
  font-weight: 600;
  font-size: 1.3em;
  color: #333;
  margin-top: 1.5em;
}
</style>
