spring:
  datasource:
    url: jdbc:mysql://223.82.75.77:3306/AYumeRNA
    username: AYumeRNA
    password: cSejdkCpH6pzFnBK
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   # ??????????, ???? validate, create, none ?
    show-sql: true        # ????? SQL ???????
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect  # Hibernate ?????
  # ?? profiles??????
  profiles:
    active: dev  # ???????????????? profile
  ai:
    openai:
      api-key: sk-svBUKMEaKNuuKFU7C2E5Ac00Bc5b498aB344AaE5De9f8b05  # ?? OpenAI API key
      api-url: https://api.lqqq.ltd/v1  # ?????????? API ??
